// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDossierMed = "Dossier_med"

// DossierMed mapped from table <Dossier_med>
type DossierMed struct {
	DateDiagnostic time.Time `gorm:"column:date_diagnostic;type:date;primaryKey" json:"date_diagnostic"`
	NNiss          string    `gorm:"column:n_niss;type:character varying;primaryKey" json:"n_niss"`
	NomPathologie  string    `gorm:"column:nom_pathologie;type:character varying;primaryKey" json:"nom_pathologie"`
}

// TableName DossierMed's table name
func (*DossierMed) TableName() string {
	return TableNameDossierMed
}
