// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMedecin = "Medecin"

// Medecin mapped from table <Medecin>
type Medecin struct {
	NInami     string  `gorm:"column:n_inami;type:character varying;not null" json:"n_inami"`
	Nom        string  `gorm:"column:nom;type:character varying;not null" json:"nom"`
	Prenom     string  `gorm:"column:prenom;type:character varying;not null" json:"prenom"`
	AMail      *string `gorm:"column:a_mail;type:character varying" json:"a_mail"`
	NTelephone *string `gorm:"column:n_telephone;type:character varying" json:"n_telephone"`
	NInamiMed  string  `gorm:"column:n_inami_med;type:character varying;primaryKey" json:"n_inami_med"`
	Specialite string  `gorm:"column:specialite;type:character varying;not null" json:"specialite"`
	NomSysAna  *string `gorm:"column:nom_sys_ana;type:character varying" json:"nom_sys_ana"`
}

// TableName Medecin's table name
func (*Medecin) TableName() string {
	return TableNameMedecin
}
