// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMedicament = "Medicament"

// Medicament mapped from table <Medicament>
type Medicament struct {
	NomMedic        string  `gorm:"column:nom_medic;type:character varying;primaryKey" json:"nom_medic"`
	Dci             *string `gorm:"column:dci;type:character varying" json:"dci"`
	Conditionnement *string `gorm:"column:conditionnement;type:character varying" json:"conditionnement"`
	NomPathologie   *string `gorm:"column:nom_pathologie;type:character varying" json:"nom_pathologie"`
}

// TableName Medicament's table name
func (*Medicament) TableName() string {
	return TableNameMedicament
}
