// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePatient = "Patient"

// Patient mapped from table <Patient>
type Patient struct {
	NNiss         string     `gorm:"column:n_niss;type:character(16);primaryKey" json:"n_niss"`
	Nom           string     `gorm:"column:nom;type:character varying;not null" json:"nom"`
	Prenom        string     `gorm:"column:prenom;type:character varying;not null" json:"prenom"`
	Genre         string     `gorm:"column:genre;type:character(1);not null" json:"genre"`
	DateNaissance *time.Time `gorm:"column:date_naissance;type:date" json:"date_naissance"`
	AMail         *string    `gorm:"column:a_mail;type:character varying" json:"a_mail"`
	NTelephone    *string    `gorm:"column:n_telephone;type:character varying" json:"n_telephone"`
	NInamiMed     *string    `gorm:"column:n_inami_med;type:character varying" json:"n_inami_med"`
	NInamiPha     *string    `gorm:"column:n_inami_pha;type:character varying" json:"n_inami_pha"`
}

// TableName Patient's table name
func (*Patient) TableName() string {
	return TableNamePatient
}
