// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePrescription = "Prescription"

// Prescription mapped from table <Prescription>
type Prescription struct {
	DateEmission    time.Time `gorm:"column:date_emission;type:date;primaryKey" json:"date_emission"`
	DureeTraitement *string   `gorm:"column:duree_traitement;type:character varying" json:"duree_traitement"`
	NNiss           string    `gorm:"column:n_niss;type:character varying;primaryKey" json:"n_niss"`
	NomMedic        string    `gorm:"column:nom_medic;type:character varying;primaryKey" json:"nom_medic"`
	NInamiMed       string    `gorm:"column:n_inami_med;type:character varying;primaryKey" json:"n_inami_med"`
	NInamiPha       *string   `gorm:"column:n_inami_pha;type:character varying" json:"n_inami_pha"`
}

// TableName Prescription's table name
func (*Prescription) TableName() string {
	return TableNamePrescription
}
