// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProSante = "Pro_sante"

// ProSante mapped from table <Pro_sante>
type ProSante struct {
	NInami     string  `gorm:"column:n_inami;type:character varying;primaryKey" json:"n_inami"`
	Nom        string  `gorm:"column:nom;type:character varying;not null" json:"nom"`
	Prenom     string  `gorm:"column:prenom;type:character varying;not null" json:"prenom"`
	AMail      *string `gorm:"column:a_mail;type:character varying" json:"a_mail"`
	NTelephone *string `gorm:"column:n_telephone;type:character varying" json:"n_telephone"`
}

// TableName ProSante's table name
func (*ProSante) TableName() string {
	return TableNameProSante
}
