// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSystemeAna = "Systeme_ana"

// SystemeAna mapped from table <Systeme_ana>
type SystemeAna struct {
	NomSysAna     string  `gorm:"column:nom_sys_ana;type:character varying;primaryKey" json:"nom_sys_ana"`
	NomPathologie *string `gorm:"column:nom_pathologie;type:character varying" json:"nom_pathologie"`
}

// TableName SystemeAna's table name
func (*SystemeAna) TableName() string {
	return TableNameSystemeAna
}
