// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"patient/model"
)

func newPathologie(db *gorm.DB, opts ...gen.DOOption) pathologie {
	_pathologie := pathologie{}

	_pathologie.pathologieDo.UseDB(db, opts...)
	_pathologie.pathologieDo.UseModel(&model.Pathologie{})

	tableName := _pathologie.pathologieDo.TableName()
	_pathologie.ALL = field.NewAsterisk(tableName)
	_pathologie.NomPathologie = field.NewString(tableName, "nom_pathologie")
	_pathologie.NomSysAna = field.NewString(tableName, "nom_sys_ana")

	_pathologie.fillFieldMap()

	return _pathologie
}

type pathologie struct {
	pathologieDo pathologieDo

	ALL           field.Asterisk
	NomPathologie field.String
	NomSysAna     field.String

	fieldMap map[string]field.Expr
}

func (p pathologie) Table(newTableName string) *pathologie {
	p.pathologieDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pathologie) As(alias string) *pathologie {
	p.pathologieDo.DO = *(p.pathologieDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pathologie) updateTableName(table string) *pathologie {
	p.ALL = field.NewAsterisk(table)
	p.NomPathologie = field.NewString(table, "nom_pathologie")
	p.NomSysAna = field.NewString(table, "nom_sys_ana")

	p.fillFieldMap()

	return p
}

func (p *pathologie) WithContext(ctx context.Context) *pathologieDo {
	return p.pathologieDo.WithContext(ctx)
}

func (p pathologie) TableName() string { return p.pathologieDo.TableName() }

func (p pathologie) Alias() string { return p.pathologieDo.Alias() }

func (p *pathologie) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pathologie) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 2)
	p.fieldMap["nom_pathologie"] = p.NomPathologie
	p.fieldMap["nom_sys_ana"] = p.NomSysAna
}

func (p pathologie) clone(db *gorm.DB) pathologie {
	p.pathologieDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pathologie) replaceDB(db *gorm.DB) pathologie {
	p.pathologieDo.ReplaceDB(db)
	return p
}

type pathologieDo struct{ gen.DO }

func (p pathologieDo) Debug() *pathologieDo {
	return p.withDO(p.DO.Debug())
}

func (p pathologieDo) WithContext(ctx context.Context) *pathologieDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pathologieDo) ReadDB() *pathologieDo {
	return p.Clauses(dbresolver.Read)
}

func (p pathologieDo) WriteDB() *pathologieDo {
	return p.Clauses(dbresolver.Write)
}

func (p pathologieDo) Session(config *gorm.Session) *pathologieDo {
	return p.withDO(p.DO.Session(config))
}

func (p pathologieDo) Clauses(conds ...clause.Expression) *pathologieDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pathologieDo) Returning(value interface{}, columns ...string) *pathologieDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pathologieDo) Not(conds ...gen.Condition) *pathologieDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pathologieDo) Or(conds ...gen.Condition) *pathologieDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pathologieDo) Select(conds ...field.Expr) *pathologieDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pathologieDo) Where(conds ...gen.Condition) *pathologieDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pathologieDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *pathologieDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p pathologieDo) Order(conds ...field.Expr) *pathologieDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pathologieDo) Distinct(cols ...field.Expr) *pathologieDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pathologieDo) Omit(cols ...field.Expr) *pathologieDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pathologieDo) Join(table schema.Tabler, on ...field.Expr) *pathologieDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pathologieDo) LeftJoin(table schema.Tabler, on ...field.Expr) *pathologieDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pathologieDo) RightJoin(table schema.Tabler, on ...field.Expr) *pathologieDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pathologieDo) Group(cols ...field.Expr) *pathologieDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pathologieDo) Having(conds ...gen.Condition) *pathologieDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pathologieDo) Limit(limit int) *pathologieDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pathologieDo) Offset(offset int) *pathologieDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pathologieDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *pathologieDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pathologieDo) Unscoped() *pathologieDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pathologieDo) Create(values ...*model.Pathologie) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pathologieDo) CreateInBatches(values []*model.Pathologie, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pathologieDo) Save(values ...*model.Pathologie) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pathologieDo) First() (*model.Pathologie, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pathologie), nil
	}
}

func (p pathologieDo) Take() (*model.Pathologie, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pathologie), nil
	}
}

func (p pathologieDo) Last() (*model.Pathologie, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pathologie), nil
	}
}

func (p pathologieDo) Find() ([]*model.Pathologie, error) {
	result, err := p.DO.Find()
	return result.([]*model.Pathologie), err
}

func (p pathologieDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Pathologie, err error) {
	buf := make([]*model.Pathologie, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pathologieDo) FindInBatches(result *[]*model.Pathologie, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pathologieDo) Attrs(attrs ...field.AssignExpr) *pathologieDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pathologieDo) Assign(attrs ...field.AssignExpr) *pathologieDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pathologieDo) Joins(fields ...field.RelationField) *pathologieDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pathologieDo) Preload(fields ...field.RelationField) *pathologieDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pathologieDo) FirstOrInit() (*model.Pathologie, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pathologie), nil
	}
}

func (p pathologieDo) FirstOrCreate() (*model.Pathologie, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pathologie), nil
	}
}

func (p pathologieDo) FindByPage(offset int, limit int) (result []*model.Pathologie, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pathologieDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pathologieDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pathologieDo) Delete(models ...*model.Pathologie) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pathologieDo) withDO(do gen.Dao) *pathologieDo {
	p.DO = *do.(*gen.DO)
	return p
}
